name = "business-docker-proxy"
compatibility_date = "2023-12-01"
# pages_build_output_dir = "pages" 

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "mwdocker.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "business-docker-proxy"
# routes = [
#   { pattern = "docker.mwdocker.top", custom_domain = true },
#   { pattern = "quay.mwdocker.top", custom_domain = true },
#   { pattern = "gcr.mwdocker.top", custom_domain = true },
#   { pattern = "k8s-gcr.mwdocker.top", custom_domain = true },
#   { pattern = "k8s.mwdocker.top", custom_domain = true },
#   { pattern = "ghcr.mwdocker.top", custom_domain = true },
#   { pattern = "cloudsmith.mwdocker.top", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "business-docker-proxy-staging"
# route = { pattern = "docker-staging.mwdocker.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
